version: '3.8'

services:
  swagger-mcp:
    # 支持多平台镜像
    image: swagger-mcp:latest
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
        - linux/arm64
        - linux/arm/v7
    container_name: swagger-mcp
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - SWAGGER_URI=${SWAGGER_URI:-https://petstore.swagger.io/v2/swagger.json}
      - PYTHONUNBUFFERED=1
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD", "python", "-c", "from swagger_mcp.server import mcp; print('OK')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    volumes:
      # 可选：挂载配置文件
      - ./config:/app/config:ro
    networks:
      - swagger-mcp-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  swagger-mcp-network:
    driver: bridge

# 开发环境配置
x-development: &development
  build:
    context: .
    target: builder  # 使用构建阶段用于开发
  volumes:
    - .:/app
    - /app/__pycache__
  environment:
    - SWAGGER_URI=${SWAGGER_URI:-https://petstore.swagger.io/v2/swagger.json}
    - PYTHONUNBUFFERED=1
    - PYTHONDONTWRITEBYTECODE=1
  command: ["python", "-m", "swagger_mcp.server"]

# 生产环境配置  
x-production: &production
  image: swagger-mcp:latest
  restart: always
  deploy:
    resources:
      limits:
        memory: 512M
        cpus: '0.5'
      reservations:
        memory: 256M
        cpus: '0.25' 